Lineage: First version of IsAppendOnly
grafana/thema pull request #123
Opened 2023-03-31 13:40 UTC by AgnesToulet

This is a first basic implementation of `IsAppendOnly(oldLineage, newLineage Lineage)` that does string comparison. 

Long-term, we probably want a more complex version that is less strict (allow authorized changes).

2023-04-24 09:25 UTC, AgnesToulet commented on lineage.go
> +	}
`lin.allsch` is an array of `*UnarySchema` so copy can't be used here.

2023-04-25 16:09 UTC, sdboyer commented on lineage.go
> +	}
hah! never realized that `copy` didn't deep-copy pointer values. TIL

2023-04-26 16:46 UTC, sdboyer requested changes
i realize this is still marked draft, but it does seem increasingly like we need to get some version of it as a prerequisite to other work.

IMO it's fine to merge this even if the comparison algorithm is flawed, so long as we're happy with the `IsAppendOnly` function signature.

2023-04-26 16:46 UTC, sdboyer commented on internal/cuetil/equal.go
> +func Equal(val1 cue.Value, val2 cue.Value) bool {
Need comment for exported func

2023-04-26 16:46 UTC, sdboyer commented on lineage.go
> +
Need comment for exported func. Probably worth noting in that comment that the comparison algorithm this currently uses is unsophisticated and subject to change

2023-04-26 16:46 UTC, sdboyer commented on lineage.go
> +func IsAppendOnly(oldLineage Lineage, newLineage Lineage) bool {
i think this is the signature we want. Even if we can't convey much in the error message right now, it'll be crucial that a failure here is able to provide line-level feedback on where the problem was.

```suggestion
func IsAppendOnly(old, new Lineage) error {
```

2023-04-27 13:27 UTC, AgnesToulet commented
Closing in favor of https://github.com/grafana/thema/pull/130

2023-04-27 13:27 UTC, closed without merging